import{useCallback,useEffect,useState}from'react';
import{Link,useNavigate}from'react-router-dom';
import type{Session}from'@supabase/supabase-js';
import{supabase}from'../lib/supabase';
import type{Child,PlayEvent}from'../types';
type ExistingRequest={status:string};type Props={event:PlayEvent;session:Session|null;unavailable:boolean;full:boolean;onRequestChange?:()=>void};
export function RequestPlace({event,session,unavailable,full,onRequestChange}:Props){
 const navigate=useNavigate();const[open,setOpen]=useState(false);const[children,setChildren]=useState<Child[]>([]);const[selected,setSelected]=useState<string[]>([]);const[adults,setAdults]=useState(1);const[message,setMessage]=useState('');const[status,setStatus]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[checkingStatus,setCheckingStatus]=useState(Boolean(session));const[submitting,setSubmitting]=useState(false);const[cancelling,setCancelling]=useState(false);const remaining=Math.max(0,event.max_children-(event.accepted_children??0));
 const loadStatus=useCallback(async()=>{if(!session){setStatus('');setCheckingStatus(false);return}const{data,error:statusError}=await supabase.from('event_requests').select('status').eq('event_id',event.id).eq('requester_id',session.user.id).maybeSingle();if(statusError)setError(statusError.message);else{const value=(data as ExistingRequest|null)?.status??'';setStatus(value==='cancelled'?'':value)}setCheckingStatus(false)},[event.id,session]);
 useEffect(()=>{setCheckingStatus(Boolean(session));void loadStatus();if(!session)return;const channel=supabase.channel(`request-status-${event.id}-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'event_requests',filter:`event_id=eq.${event.id}`},()=>{void loadStatus();onRequestChange?.()}).subscribe();const visible=()=>{if(document.visibilityState==='visible')void loadStatus()};document.addEventListener('visibilitychange',visible);return()=>{document.removeEventListener('visibilitychange',visible);void supabase.removeChannel(channel)}},[event.id,session,loadStatus,onRequestChange]);
 async function begin(){if(!session){navigate(`/auth?next=${encodeURIComponent(`/events/${event.id}`)}`);return}setLoading(true);setError('');const{data:existing}=await supabase.from('event_requests').select('status').eq('event_id',event.id).eq('requester_id',session.user.id).maybeSingle();if(existing&&(existing as ExistingRequest).status!=='cancelled'){setStatus((existing as ExistingRequest).status);setLoading(false);return}const{data,error:kidsError}=await supabase.from('children').select('id,nickname,age_band,interests,participation_notes').eq('parent_id',session.user.id).order('created_at');setLoading(false);if(kidsError){setError(kidsError.message);return}setChildren((data??[])as Child[]);setOpen(true)}
 function toggle(id:string){setSelected(current=>{if(current.includes(id))return current.filter(x=>x!==id);if(current.length>=event.max_children){setError(`This event allows at most ${event.max_children} ${event.max_children===1?'child':'children'} per request.`);return current}setError('');return[...current,id]})}
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected.length){setError('Choose at least one child profile.');return}setSubmitting(true);setError('');const{data,error:requestError}=await supabase.rpc('request_event_place',{p_event_id:event.id,p_child_ids:selected,p_adult_count:adults,p_message:message.trim()||null});setSubmitting(false);if(requestError){setError(requestError.message);return}setStatus(String(data));setOpen(false);onRequestChange?.()}
 async function cancelPlace(){if(!window.confirm('Cancel your place at this event? The space will become available to another family.'))return;setCancelling(true);setError('');const{error:cancelError}=await supabase.rpc('cancel_event_place',{p_event_id:event.id});setCancelling(false);if(cancelError){setError(cancelError.message);return}setStatus('');onRequestChange?.()}
 if(checkingStatus)return <div className="request-status-loading" aria-live="polite"><div className="spinner"/>Checking your place…</div>;
 if(status)return <div className={`request-confirmation request-${status}`} role="status"><b>{status==='accepted'?'Your place is confirmed':status==='waitlisted'?'You are on the waitlist':status==='pending'?'Your request is pending':status==='place_offered'?'A place has been offered':status==='declined'?'Your request was declined':status==='cancelled'?'Your place was cancelled':`Request ${status.replace('_',' ')}`}</b><p>{status==='accepted'?'You are already attending this event.':status==='pending'?'The organizer will review your request.':status==='cancelled'?'The child places are available to other families again.':'You can follow updates in My activities.'}</p>{status==='accepted'?<button className="button secondary small danger" disabled={cancelling} onClick={cancelPlace}>{cancelling?'Cancelling…':'Cancel my place'}</button>:status!=='cancelled'&&<Link to="/activities" className="button secondary small">View my activities</Link>}{error&&<p className="field-error" role="alert">{error}</p>}</div>;
 if(!open)return <><button className="button" onClick={begin} disabled={unavailable||loading}>{loading?'Loading…':unavailable?'Joining unavailable':full?'Join waitlist':'Request a place'}</button>{full&&!unavailable&&<p className="capacity-warning">This event is full. You can join the waitlist and the organizer will contact you if a place opens.</p>}{error&&<p className="field-error" role="alert">{error}</p>}</>;
 const willWaitlist=selected.length>remaining;
 return <form className="request-form" onSubmit={submit}><fieldset><legend>Who is joining?</legend><p className="capacity-warning">{full?`This event is full. Choose up to ${event.max_children} ${event.max_children===1?'child':'children'} to join the waitlist.`:`${remaining} child ${remaining===1?'place':'places'} currently remaining. Maximum ${event.max_children} per request.`}</p>{children.length?children.map(child=>{const disabled=!selected.includes(child.id)&&selected.length>=event.max_children;return <label className={`request-child ${disabled?'disabled':''}`} key={child.id}><input type="checkbox" checked={selected.includes(child.id)} disabled={disabled} onChange={()=>toggle(child.id)}/><span><b>{child.nickname}</b><small>{child.age_band} years</small></span></label>}):<p>No child profiles found. <Link to="/profile">Add one in your profile</Link>.</p>}</fieldset><label>Adults attending<input type="number" min={1} max={20} value={adults} onChange={e=>setAdults(Number(e.target.value))}/></label><label>Message to organizer (optional)<textarea maxLength={500} value={message} onChange={e=>setMessage(e.target.value)}/></label>{error&&<p className="field-error" role="alert">{error}</p>}<div className="actions"><button className="button small" disabled={submitting||!children.length}>{submitting?'Sending…':willWaitlist?'Join waitlist':'Send request'}</button><button type="button" className="button secondary small" onClick={()=>setOpen(false)}>Cancel</button></div></form>
}
