create or replace function public.request_event_place(p_event_id uuid,p_child_ids uuid[],p_adult_count integer default 1,p_message text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_event public.events%rowtype;v_request_id uuid;v_status public.event_request_status;v_child_count integer;v_valid_children integer;v_accepted integer;
begin
if auth.uid() is null or not public.is_active_parent() then raise exception 'Complete onboarding before requesting a place';end if;v_child_count:=coalesce(array_length(p_child_ids,1),0);if v_child_count<1 or v_child_count>20 then raise exception 'Choose between 1 and 20 child profiles';end if;if p_adult_count<1 or p_adult_count>20 then raise exception 'Choose between 1 and 20 adults';end if;if length(coalesce(p_message,''))>500 then raise exception 'Message is too long';end if;
select * into v_event from public.events where id=p_event_id for update;if not found or v_event.status<>'published' or v_event.registration_status<>'open' or v_event.ends_at<=now() or v_event.is_example then raise exception 'This event is not accepting requests';end if;if v_event.organizer_id=auth.uid() then raise exception 'You cannot request your own event';end if;
select count(*) into v_valid_children from public.children c where c.id=any(p_child_ids) and c.parent_id=auth.uid() and c.age_band=any(v_event.age_bands);if v_valid_children<>v_child_count then raise exception 'Choose only your own child profiles in a suitable age band';end if;select coalesce(sum(child_count),0) into v_accepted from public.event_requests where event_id=p_event_id and status='accepted';v_status:=case when v_accepted+v_child_count>v_event.max_children then 'waitlisted'::public.event_request_status else 'pending'::public.event_request_status end;
insert into public.event_requests(event_id,requester_id,status,child_count,adult_count,message) values(p_event_id,auth.uid(),v_status,v_child_count,p_adult_count,nullif(trim(p_message),'')) returning id into v_request_id;insert into public.event_request_children(event_request_id,child_id) select v_request_id,unnest(p_child_ids);insert into public.notifications(user_id,type,title,body,action_url) values(auth.uid(),'request_created','Place requested','Your request for '||v_event.title||' was sent.','/activities'),(v_event.organizer_id,'new_event_request','New place request','A parent requested a place at '||v_event.title||'.','/activities');return v_request_id;
end$$;
revoke all on function public.request_event_place(uuid,uuid[],integer,text) from public;grant execute on function public.request_event_place(uuid,uuid[],integer,text) to authenticated;
